### ISSUE TITLE
winner-plus-propagation-loss-model.h: No such file or directory

### ISSUE THREAD

**Issue by danielrluna** [tudo-cni/ns3-lena-nb#1]
Hi,

Firstly,  congratulations on your work and thank you for make this repository public.

Well, I have been trying to installing ns3-lena-nb, but I've come across this error:

![Selection_163](https://user-images.githubusercontent.com/50034390/217649109-2063e0aa-84a2-4490-81e1-fc724b1e92ab.png)

I did everything as instructed and I guess that this file is missing (I am using python 3.6). Also, which  commando "./waf configure" are you using? Maybe I am using the wrong one.

BR.

**Comment by komplike** [comment]
Hi @danielrluna ,
I'm working with lena-nb currently and I have to admit there is a lot of dependency issues to fix before it works, but it's all within ones programming skills in my opinion. If you search for the missing module you'll come back to [tudo-cni](https://github.com/tudo-cni) repository but the [propagation model subdir](https://github.com/tudo-cni/ns3-propagation-winner-plus).  

Make sure you **include all** of it's contains to your ns3 and it should work. Also, if you come accross some dependency issue, it should be easy to fix just following the compiller message(I experienced a few).

At last, waf configuration is working for me with **--disable-python** option as there are some problems with ns3.32 and python these days.

Hope this helps and have fun experimenting.

**Comment by pjoerke** [comment]
Sorry for that. We added an additional note regarding the missing propagation model in the lena-nb readme.

**Comment by danielrluna** [comment]
Thank you for the attention. We have managed to get  it working.  

BR.
