### ISSUE TITLE
Couldn't find the specified program:

### ISSUE THREAD

**Issue by htahir6200** [tudo-cni/ns3-lena-nb#2]
Hello!

Thanks for sharing such a nice project. I am a phd student and working on studying the energy efficiency for NB-IoT. I came across the project and configured all the project as specifies apart from the ns3 version (I am using ns-3.37) due the fact that mac M1 only supports that. 

After running some of the other examples, when I started with lena-nb-5G, it gave me the following error. could you guide me a little if i am doing anything wrong? I have am new to ns-3. 

```
ahiabba@FVFH5170Q05N ns-3.37 % ./ns3 run src/lte/examples/lena-nb-5G-scenario.cc                                                                                   
Traceback (most recent call last):
  File "/Users/tahiabba/ns-allinone-3.37/ns-3.37/./ns3", line 1546, in <module>
    main()
  File "/Users/tahiabba/ns-allinone-3.37/ns-3.37/./ns3", line 1483, in main
    raise Exception("Couldn't find the specified program: %s" % target_to_run)
Exception: Couldn't find the specified program: src/lte/examples/lena-nb-5G-scenario.cc
```

**Comment by tngebauer** [comment]
Hi, 
thank you very much for you interest into our project. 
As stated in the README, Lena-NB is based on ns3.32 and is only intented to be run on that version. While migrating LENA-NB to newer ns3 versions is somewhere on our roadmap, we are currently not able to assist you, as we also haven't worked with newer version yet. 

For an exemplary call of the LENA-NB simulations (ns3.32 **!** ) you can compare the `example_runner.py` script.
Also, we highly suggest getting familiar with general ns3 (official documentation and tutorial) before working with more advanced frameworks like LENA and equally LENA-NB.
